### ISSUE TITLE
workflow/arduino.yml not rendering properly

### ISSUE THREAD

**Issue by zeulewan** [mirzafahad/ci_arduino_project#1]
You don't have issues enabled on your https://github.com/mirzafahad/mirzafahad.github.io repo. 

On your website: https://mirzafahad.github.io/2021-03-09-github-cicd-for-arduino-projects/ your yml file is not rendering properly.

<img width="782" alt="Screenshot 2023-11-18 at 1 30 45 AM" src="https://github.com/mirzafahad/ci_arduino_project/assets/55005377/6fc18448-ed3f-4a51-8870-e51ce4816872">

The code in your yml file is: 

```
# We then install the platform, which one will be determined
      # dynamically by the build matrix.
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./Blink --warnings more
```

**Comment by mirzafahad** [comment]
@zeulewan Thank you for noticing that. I have fixed it.
